import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Header from "@/components/shared/header";
import Footer from "@/components/shared/footer";
import SessionProviders from "@/components/providers/sessionProvider";
import ConditionalPopUpHeader from "@/components/home_components/popHeaderClient";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col relative`}
      >
        <SessionProviders>
          {/*<ThemeProvider>*/}
          <ConditionalPopUpHeader/>
          <Header />

          <main className="grow">
            {children}
          </main>

          <Footer />
         {/* <ThemeController />
        </ThemeProvider>*/}
      </SessionProviders>
        
      </body>
    </html>
  );
}
